class User {
  final String id,
      companyLogo,
      companyName,
      customerName,
      customerPhoneNumber,
      companyAcctNum,
      companyAcctName,
      bankName,
      date,
      modeofpayment,
      item,
      quantity,
      price,
      amountPaid,
      total,
      balance,
      dueDate,
      itemTwo,
      quantityTwo,
      priceTwo,
      amountPaidTwo,
      itemThree,
      quantityThree,
      priceThree,
      amountPaidThree,
      itemFour,
      quantityFour,
      priceFour,
      amountPaidFour,
      itemFive,
      quantityFive,
      priceFive,
      amountPaidFive,
      totalAmountPaid,
      session,
      term,
      studentClass,
      uid;
  var itemSix,
      quantitySix,
      priceSix,
      amountPaidSix,
      itemSeven,
      quantitySeven,
      priceSeven,
      amountPaidSeven,
      itemEight,
      quantityEight,
      priceEight,
      amountPaidEight,
      itemNine,
      quantityNine,
      priceNine,
      amountPaidNine,
      itemTen,
      quantityTen,
      priceTen,
      amountPaidTen;
  User(
      {required this.id,
      required this.customerName,
      required this.companyName,
      required this.companyLogo,
      required this.customerPhoneNumber,
      required this.companyAcctNum,
      required this.companyAcctName,
      required this.bankName,
      required this.date,
      required this.modeofpayment,
      required this.item,
      required this.quantity,
      required this.price,
      required this.amountPaid,
      required this.itemTwo,
      required this.quantityTwo,
      required this.priceTwo,
      required this.amountPaidTwo,
      required this.itemThree,
      required this.quantityThree,
      required this.priceThree,
      required this.amountPaidThree,
      required this.itemFour,
      required this.quantityFour,
      required this.priceFour,
      required this.amountPaidFour,
      required this.itemFive,
      required this.quantityFive,
      required this.priceFive,
      required this.amountPaidFive,
      required this.total,
      required this.balance,
      required this.dueDate,
      required this.totalAmountPaid,
      required this.session,
      required this.term,
      required this.studentClass,
      required this.uid,
      this.itemSix,
      this.quantitySix,
      this.priceSix,
      this.amountPaidSix,
      this.itemSeven,
      this.quantitySeven,
      this.priceSeven,
      this.amountPaidSeven,
      this.itemEight,
      this.quantityEight,
      this.priceEight,
      this.amountPaidEight,
      this.itemNine,
      this.quantityNine,
      this.priceNine,
      this.amountPaidNine,
      this.itemTen,
      this.quantityTen,
      this.priceTen,
      this.amountPaidTen});

  Map<String, dynamic> toJson() => {};
  static User fromJson(Map<String, dynamic> json) => User(
        customerName: json['customerName'],
        id: json['id'],
        companyName: json['companyName'],
        companyLogo: json['companyLogo'],
        customerPhoneNumber: json['customerPhoneNumber'],
        companyAcctNum: json['companyAccountNumber'],
        companyAcctName: json['companyAccountName'],
        bankName: json['bank'],
        date: json['date'],
        modeofpayment: json['modeOfPayment'],
        item: json['item'],
        quantity: json['quantity'],
        price: json['price'],
        amountPaid: json['amountPaid'],
        itemTwo: json['itemTwo'],
        quantityTwo: json['quantityTwo'],
        priceTwo: json['priceTwo'],
        amountPaidTwo: json['amountPaidTwo'],
        itemThree: json['itemThree'],
        quantityThree: json['quantityThree'],
        priceThree: json['priceThree'],
        amountPaidThree: json['amountPaidThree'],
        itemFour: json['itemFour'],
        quantityFour: json['quantityFour'],
        priceFour: json['priceFour'],
        amountPaidFour: json['amountPaidFour'],
        itemFive: json['itemFive'],
        quantityFive: json['quantityFive'],
        priceFive: json['priceFive'],
        amountPaidFive: json['amountPaidFive'],
        total: json['total'],
        balance: json['balance'],
        dueDate: json['dueDate'],
        totalAmountPaid: json['totalAmountPaid'],
        session: json['session'],
        term: json['term'],
        studentClass: json['studentClass'],
        uid: json['uid'],
        itemSix: json['itemSix'],
        quantitySix: json['quantitySix'],
        priceSix: json['priceSix'],
        amountPaidSix: json['amountPaidSix'],
        itemSeven: json['itemSeven'],
        quantitySeven: json['quantitySeven'],
        priceSeven: json['priceSeven'],
        amountPaidSeven: json['amountPaidSeven'],
        itemEight: json['itemEight'],
        quantityEight: json['quantityEight'],
        priceEight: json['priceEight'],
        amountPaidEight: json['amountPaidEight'],
        itemNine: json['itemNine'],
        quantityNine: json['quantityNine'],
        priceNine: json['priceNine'],
        amountPaidNine: json['amountPaidNine'],
        itemTen: json['itemTen'],
        quantityTen: json['quantityTen'],
        priceTen: json['priceTen'],
        amountPaidTen: json['amountPaidTen'],
      );
}
